### ISSUE TITLE
Cannot install from marketplace

### ISSUE THREAD

**Issue by r43** [IamSAB/pagekit-form#4]
Hello,

I wanted to install it like a substitution for form maker but it gives me an error.
![cant_install](https://user-images.githubusercontent.com/33175034/54028793-8435b680-41a6-11e9-97f2-e5eb9062a2b1.png)

**Comment by IamSAB** [comment]
Please then try do install it via System > Extension as proposed in the extension description. The zip you can download from here.

I know about this issue, but could not resolve it, as the code of the marketplace is not opensource and the interface does not give any hint about possible errors.
